routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('test', 'TestController');
/*Route::get('test', ['as'=>'test.index','uses'=>'TestController@index']);
Route::get('test/{id}/edit', ['as'=>'test.edit','uses'=>'TestController@edit']);
Route::get('test/{id}', ['as'=>'test.show','uses'=>'TestController@show']);
Route::delete('test/{id}/edit', ['as'=>'test.destroy','uses'=>'TestController@edit']);*/

/*Route::get('user/{id}', function($id){
  return 'Bienvenido user:'.$id;
});*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
  Route::resource('users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

Route::get('products', ['as'=>'products.index','uses'=>'ProductController@index']);
Route::get('product/create', ['as'=>'product.create','uses'=>'ProductController@create']);
Route::post('product/store', ['as' => 'product.store', 'uses' => 'ProductController@store']);
Route::get('product/edit/{id}', ['as' => 'product.edit', 'uses' => 'ProductController@edit']);
Route::patch('product/{id}', ['as' => 'product.update', 'uses' => 'ProductController@update']);
Route::delete('product/{id}', ['as' => 'product.destroy', 'uses' => 'ProductController@destroy']);
Route::get('product/{id}',['as' => 'product.show', 'uses' => 'ProductController@show']);

app/User.php
<?php

namespace App;

use App\Profile;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profiles(){
      return $this->belongsToMany('App\Profile');
    }

    public function hasAnyProfiles($profiles){
        if($this->profiles()->whereIn('name', $profiles)->first()){
            return true;
        }
        return false;
    }

    public function hasProfile($profile){
        if($this->profiles()->where('name', $profile)->first()){
            return true;
        }
        return false;
    }

    public function scopeName($query, $name)
    {
        if (trim($name) != "")
        {
            $query->where('name', "LIKE", "%$name%");
        }
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Profile;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator ;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       // $users= User::all();
       $users = User::name($request->get('name'))->orderBy('id', 'DESC')->paginate();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        
        if(Gate::denies('edit-users')){
            return redirect(route('admin.users.index'));
        }
        
        $profiles = Profile::all();
        return view('admin.users.edit')->with([
            'user' => $user,
            'profiles' => $profiles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->profiles()->sync($request->profiles);

        $user->name = $request->name;
        $user->email = $request->email;
        if($user->save()){
            $request->session()->flash('success', $user->name. ' ha sido actualizado');
        }else{
            $request->session()->flash('error', 'Ocuarrió un error no se actualizó el usuario');
        }

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if(Gate::denies('edit-users')){
            return redirect(route('admin.users.index'));
        }
        
        $user->profiles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editar Usuarios</div>

                <div class="card-body">
                    <form action="{{route('admin.users.update', $user)}}" method="POST">

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        @csrf
                        {{method_field('PUT')}}
                        <div class="form-group row">
                        <label for="profiles" class="col-md-4 col-form-label text-md-right">Perfiles</label>
                        <div class="col-md-6">
                        @foreach($profiles as $profile)
                            <div class="form-check">
                                <input type="checkbox" name="profiles[]" value="{{ $profile->id}}"
                                @if($user->profiles->pluck('id')->contains($profile->id)) checked 
                                @endif >
                                <label>{{$profile->name}}</label>
                            </div>
                        @endforeach
                        </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Actualizar
                        </button>
                    </form>
                    @include('partials.box-back')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
        <h1>
            Busqueda de usuarios
            {{ Form::open(['route' => 'admin.users.index', 'method' => 'GET', 'class' => 'form-inline pull-right']) }}
                <div class="form-group">
                    {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nombre']) }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Buscar
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            {{ Form::close() }}
        </h1>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Usuarios</div>

                <div class="card-body">
                <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Correo Electrónico</th>
                  <th scope="col">Perfil</th>
                  <th scope="col">Acciones</th>
                </tr>
              </thead>
              <tbody>
                @foreach($users as $user)
                  <tr>
                    <th scope="row">{{$user->id}}</th>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{ implode(', ', $user->profiles()->get()->pluck('name')->toArray())}}</td>
                    <td>
                      @can('edit-users')
                      <a href="{{ route('admin.users.edit', $user->id)}}"><button type="button" class="btn btn-primary float-left">Editar</button></a>
                      @endcan
                      @can('delete-users')
                      <form action="{{ route('admin.users.destroy', $user)}}" method="POST" class="float-left">
                        @csrf
                        {{method_field('DELETE')}}
                        <button type="submit" class="btn btn-warning">Eliminar</button>
                      </form>
                      @endcan
                    </td>
                    
                  </tr>
                @endforeach
              </tbody>
            </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection